#!/bin/bash

for level in 1 2 3 4 5 6 7 8 9
do
	export level
	# Replace gzipDataBinary with gzipDataAscii on the next line to test Ascii instead.
	find gzipDataBinary -type f ! -name '*.*' -exec sh -c 'TIMEFORMAT=%R; time gzip -f -v -$level {}; time gzip -d -f {}' 2> "gzipbin${level}" \; -exec echo Level ${level}: {} \;
done